#!/usr/bin/env python
"""tictactoe: This isn’t a complete tic-tac-toe game—for instance, 
  it doesn’t ever check whether a player has won—but it’s enough 
  to see how data structures can be used in programs."""

theBoard = {'top-L': ' ', 'top-M': ' ', 'top-R': ' ', 'mid-L': ' ', \
            'mid-M': ' ', 'mid-R': ' ', 'low-L': ' ', 'low-M': ' ', \
            'low-R': ' '}

def printBoard(board):
    print(board['top-L'] + '|' + board['top-M'] + '|' + board['top-R'])
    print('-+-+-')
    print(board['mid-L'] + '|' + board['mid-M'] + '|' + board['mid-R'])
    print('-+-+-')
    print(board['low-L'] + '|' + board['low-M'] + '|' + board['low-R'])

turn = 'X'
for i in range(9):
    printBoard(theBoard)
    print('Turn for ' + turn + '. Move on which space?')
    move = input()
    theBoard[move] = turn
    turn = 'O' if turn == 'X' else 'X'
    
printBoard(theBoard)
